update-dependencies:
    docker:
        - image: maven:3.8.4-openjdk-17
    working_directory: /plugin-parent-pom
    steps:
        - checkout

        - run:
            name: update-dependencies
            command: bash .circleci/bash-update-dependencies.bash
